# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-10-16T03:36:32Z"
  labels:
    app: pantheon
  name: pantheon
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - exec java $JAVA_OPTS -jar org.apache.sling.starter.jar $SLING_OPTS
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: pantheon
    - name: container
      value: podman
    - name: JAVA_HOME
      value: /usr/lib/jvm/java-1.8-openjdk/jre
    - name: JAVA_VERSION
      value: 8u191
    - name: JAVA_ALPINE_VERSION
      value: 8.191.12-r0
    - name: JAVA_OPTS
      value: -Xmx512m
    - name: SLING_OPTS
      value: -Dsling.run.modes=oak_mongo -Doak.mongo.uri=mongodb://localhost:27017
    - name: LANG
      value: C.UTF-8
    image: docker.io/apache/sling:latest
    name: sling
    ports:
    - containerPort: 5005
      hostPort: 5005
      protocol: TCP
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /opt/sling/
  - command:
    - mongod
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: pantheon
    - name: container
      value: podman
    - name: JSYAML_VERSION
      value: 3.13.0
    - name: MONGO_PACKAGE
      value: mongodb-org
    - name: MONGO_MAJOR
      value: "4.2"
    - name: GPG_KEYS
      value: E162F504A20CDF15827F718D4B7C549A058F8B6B
    - name: MONGO_REPO
      value: repo.mongodb.org
    - name: MONGO_VERSION
      value: 4.2.0
    - name: GOSU_VERSION
      value: "1.11"
    image: docker.io/library/mongo:latest
    name: slingmongo
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /
status: {}

