[id='con-pantheon-yaml-file_{context}']

= The Pantheon configuration file

In order to use a Git repository to import content to Pantheon, you need to create a configuration file in the root directory of your repository named `pantheon2.yml`. This yaml file indicates to Pantheon that it can interact with files in the repository.

The configuration file enables the following:

* Importing content from a Git repository into Pantheon
* Uploading modules into Pantheon using the uploader tool

The configuration file defines the following:

`server`:: The URL of the Pantheon server.
`repository`:: A unique ID to reference the URL of the repository. You specify the actual URL of the repository when you synchronize the repository the first time.
`modules`:: Patterns for modules that will show up in the search results on Pantheon.
`resources`:: Image files, legal information or other content that is not.

You need to define the values for `server` and `repository`.

.Example configuration file

// [options="nowrap" subs="normal"]
----
# Config file for Pantheon
## server: Pantheon server URL
## repository: a unique name, which is visible in the user facing URL

## Note: Due to yaml syntax, any filepaths that start with a wildcard must be surrounded in quotes like so:
# modules:
#  - '*.adoc'

server: http://pantheon2.int.us-west.aws.prod.paas.redhat.com[]
repository: repo_id

modules:
 - master.adoc
 - modules/*.adoc

resources:
 - shared/legal.adoc
 - shared/foreword.adoc
 - resources/*
''')
----
