[id="about-xrefs-validation-in-pantheon_{context}"]
= About xref validation in Pantheon

[role="_abstract"]
When you upload a Git repository to {ProductShortName}, each module and assembly in the repository is built as an html document. During this build, {ProductShortName} checks whether xrefs in each module and assembly are valid.

If {ProductShortName} finds invalid xrefs in a module or assembly, a red alert icon is displayed alongside it in the Search Page.

Only the following forms of xref are validated:
 
---- 
xref:document-b.adoc#target-section[Target section]
---- 

----
xref:../modules/document-c.adoc[Content C]
----

[discrete]
== Example of using xref in {ProductShortName}

In the this example, the following are the source and targets:

source document:: `document-a.adoc` 
targets::
+
** A section called `target section` in a document `document-b.adoc.`
** A document `document-c.adoc`.

Use xrefs as follows:

* To cross-reference section `target section` in `document-b.adoc` from `document-a.adoc`, use the following form:
+
----
xref:document-b.adoc#target-section[target section] 
----
+
where `target-section` is the anchor for target section.

* To cross-reference document `document-c.adoc` from `document-a.adoc`, use the following form:
+
----
xref:../modules/document-c.adoc[Section C]
----
+
where `../modules/document-c.adoc` is the path to `document-c.adoc` relative to `document-a.adoc`. 
