[id='about-pantheon']
= About Pantheon

Pantheon is a publishing platform developed by Red Hat. You can use it to publish documents based on asciidoc source. With Pantheon 2, you can create modular documents, within the browser, to suit different user stories.

The traditional content model resembled a book, with chapters and a table of contents, but Pantheon 2 provides Red Hat customers  curated paths through independent and reusable content to allow for a much richer and targeted user experience.

?? We use assemblies to put modules together into a document. So what exactly can you do with Pantheon 2? How does it help you create modular docs? ??

Pantheon 2 is designed to support the creation of smaller, independent pieces of content.

Pantheon 2 can include content from both upstream and downstream sources.

Pantheon 2 provides a GUI for managing modules and assemblies, including search and workflow features that are more user-friendly than those currently available.

Pantheon 2 includes a module library that enables content reuse.



Pantheon 2 includes
