[id='about-pantheon_{context}']
= About {ProductShortName}

{ProductShortName} is a content-management system and publishing platform developed by Red Hat.
You can use it to publish documents based on AsciiDoc source.
After adding your modules and assemblies to {ProductShortName}, you can do the following, depending on the permissions of your assigned role:

. Add metadata
. Preview your content as it displays on the Customer Portal
. Associate modules and assemblies with a product
. Publish and unpublish your content

The following table describes features that {ProductShortName} does and does not provide.

.{ProductShortName} Features
|===
|{ProductShortName} provides: |{ProductShortName} does not provide:

a|* A Graphical User Interface (GUI) for managing modules and assemblies. You can now search for specific content. {ProductShortName} {ProductNumber} also has better workflow features than {ProductShortName} {ProductNumberPrevious}.
* Metadata editing so that you can optimize content for search engines.
* A module library that enables content reuse.
* A visual preview of a module, so that you can see how it displays on the Customer Portal.

a|* A way to define the appearance of content.
* Source control. Git is the source control system.
|===

.{ProductShortName} authoring workflow

The following steps walk through the general flow of adding new content in {ProductShortName}:

. Write your content as modular documentation. Use modules and assemblies, as needed.
. Commit and push your content to GitLab or GitHub.
. When you're ready to publish your content, import it to {ProductShortName} from GitHub or GitLab.
. Use {ProductShortName} to add metadata.
. Publish the content.
