[id='pantheon-yaml-file_{context}']

= The {ProductShortName} configuration file

You need to create a configuration file, named `pantheon2.yml`, in the root directory of your repository, to enable a Git repository as a source that {ProductShortName} can use to import content. This yaml file provides necessary information that {ProductShortName} uses to interact with files in the repository.

The configuration file enables the following:

* Importing content from a Git repository into {ProductShortName}
* Uploading modules into {ProductShortName} using the Uploader tool

The configuration file defines the following:

`server`:: The URL of the {ProductShortName} server.
`repositories`:: a multi-valued structure with the following child members:
+
`name`:: A unique ID that {ProductShortName} uses to reference the URL of the repository. You specify the actual URL of the repository when you synchronize the repository the first time.
`modules`:: Patterns for modules that show up in the search results on {ProductShortName}.
`resources`:: Image files, legal information or other content that is not a complete module or assembly.
`attributes`:: a path to the repository-wide attributes file that your documents may depend on.

You need to define the values for `server` and `repository`.

.Example configuration file

// [options="nowrap" subs="normal"]
----
# Config file for {ProductShortName}

## Note: Due to yaml syntax, any filepaths that start with a wildcard must be surrounded in quotes like so:
# modules:
#  - '*.adoc'

server: {server_url}
# Example
# server: http://{ProductShortName}.redhat.com[]
repositories:
  - name: repo_id
    attributes: path/to/attribute.adoc

    modules:
      - master.adoc
      - modules/*.adoc

    resources:
      - shared/legal.adoc
      - shared/foreword.adoc
      - resources/*
----
