[id='pantheon-yaml-file_{context}']
= Description of the {ProductShortName} configuration file

[role="_abstract"]
The configuration file, named `pantheon2.yml`, resides in the root directory of your documentation repository. You use this file to designate a Git repository as a source that {ProductShortName} can use to import content. This configuration file provides the information necessary for {ProductShortName} to interact with files in the repository.

////
Keeping this section because the status of the Uploader tool is not clear. It might be relevant in the future.
The configuration file enables you to perform the following actions:
* Import content from a Git repository into {ProductShortName}
* Upload {ContentTerm} into {ProductShortName} using the Uploader tool
////

The configuration file enables you to import content from a Git repository into {ProductShortName}.

The {ProductShortName} configuration file defines the following parameters:

`server`:: (Required) The URL of the {ProductShortName} server.
`repository`:: (Required) The name of the repository. It is recommended not to include spaces in the repository name.
`variants`:: (Required) Separate sets of output built on the same set of files and differentiated by these values: `name`, `path`, and `canonical`. Modules and assemblies can have variants to differentiate how they are used, and what output is created.
+
** `name` (Optional) A unique ID that is displayed in URLs on the {ProductShortName} site when you view modules and assemblies. If no value is provided for `name`, this field is defined as *DEFAULT*.
+
For example, if you specify `name: rhel_docs`, and one of your files is named [filename]`foo.adoc`, the module's URL in {ProductShortName} is:
`\https://<_{ProductShortName}__url>/content/repositories/*repository*/entities/modules/getting_started/foo.adoc.preview`
** `path` (Optional) The path containing resource files, such as `attributes.adoc`. For more information, see xref:con-about-document-attributes_setting-up-tools[About document attributes].
** `canonical` (Required) The primary variant of content. If a search engine sees multiple variants of the same piece of content (HTML page or a group of pages) it needs to know what the primary or original one is to establish ranking. Declaring a piece of content as `canonical` tells the search engine to treat that piece of content as the canonical variant. The canonical declaration is transformed into HTML meta data. Possible values: `*true*` or `*false*`.

`assemblies`:: (optional) The path to assemblies in the repository that should be uploaded. The path can include specific files or a pattern, such as `*.adoc` to include only `.adoc` files, or `**` to include all files.
`modules`:: Path to modules in the repository that should be uploaded.
`resources`:: (optional) Attributes, image files, snippets, legal information, or other content that is not a complete module or assembly.

[NOTE]
====
File paths can indicate specific files, or file patterns. For example:

* This will upload everything inside `assemblies/`: `assemblies/**`
* This will only upload `.adoc` files inside `assemblies/`: `assemblies/*.adoc`
====

.Examples of variants:

** Document level - _Installing RHV using the command line_; _Installing RHV using the Administration Portal_.
** Module level - The same module is published in multiple Red Hat documents, such as _Red Hat Decision Manager_, _Red Hat Process Automation Manager_.

.Example YAML file with multiple variants
[source,yaml,options="nowrap",subs="attributes+,+quotes"]
----
server: https://pantheon.corp.redhat.com
repository: rhel-docs
variants:
  - name: rhel9
    path: rhel-9/common-content/attributes.adoc
    canonical: true
  - name: rhel8
    path: rhel-8/common-content/attributes.adoc
    canonical: false
assemblies:
  - rhel/assemblies/*.adoc
modules:
  - rhel/modules/*.adoc
resources:
  - images/*.png
----

In the above example, the assemblies and modules for both rhel9 and rhel8 variants are in the same directories, `rhel/assemblies/` and `rhel/modules/`. Depending on the value of their attributes, {ProductShortName} creates the separate variants.

.Example {ProductShortName} configuration file
[source,yaml,options="nowrap",subs="attributes+,+quotes"]
----
# Config file for {ProductShortName}

## Note: Due to yaml syntax, any filepaths that start with a wildcard must be surrounded in quotes like so:
# modules:
#  - '*.adoc'

server: {server_url}
# Example
# server: {ProductUrl}[]
repositories:
  - name: repo_id
    attributes: path/to/attribute.adoc

    modules:
      - master.adoc
      - modules/*.adoc

    resources:
      - shared/legal.adoc
      - shared/foreword.adoc
      - resources/*
----
