// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>



[id="con_about-assemblies_{context}"]
= About Assemblies

[role="_abstract"]
In {ProductName} {ProdctNumber}, each assembly encompasses a single user story. An assembly can include concept, procedure, or reference modules but all modules in an assembly must relate to that specific user story. Previously, many Red Hat documentation teams used assemblies as the structure of user guides and other "books." In {ProductName} {ProductNumber}, there are no books, only user stories, with one assembly per user story. This change is part of our efforts to make it easier for users to search for each specific action they want to perform. 

Link:https://redhat-documentation.github.io/modular-docs/#forming-assemblies[Assemblies] are discussed in detail in our company's description of modular documentation. Here are specific guidelines for creating assemblies in {ProductName} {ProductNumber}:

* Because each assembly relates to a single user story, you must break down an assembly that currently relates to a "book" into independent assemblies.
* Nesting assemblies is not supported.
* Each assembly relates to a single product. Although a specific solution for a customer might involve a combination of several products, {ProductName} {ProductNumber} currently only supports single-product searches. It is expected that later versions of {ProductName} will support multi-product searches, in which case an assembly that included modules from different products could be created, but for now, each assembly must relate to a single product.
