// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>



[id="con_about-assemblies_{context}"]
= Overview of assemblies
:_module-type: CONCEPT

[role="_abstract"]
In {ProductName} {ProdctNumber}, each assembly encompasses a single user story. Previously, an assembly could include multiple user stories, with only one assembly being used for a complete user guide. However, in {ProductName} {ProductNumber}, each user story requires a separate guide.

Focusing on single user stories is part of the Flexible Customer Content (FCC) effort at Red Hat. One of the goals of this approach is to make it easier for users to search for each specific action they want to perform.

Assemblies in {ProductName} {ProductNumber} must conform with the following guidelines, in addition to regular documentation guidelines:

* Existing assemblies that relate to more than one user story must be broken down into assemblies that describe one user story each.
* Nesting assemblies is currently not supported but will be in the future.
* Each assembly relates to a single product. Although a specific solution for a customer might involve a combination of several products, {ProductName} {ProductNumber} currently only supports single-product searches. It is expected that later versions of {ProductName} will support multi-product searches, allowing assemblies that include modules relating to different products.

[role="_additional-resources"]
.Additional resources

Link:https://redhat-documentation.github.io/modular-docs/#forming-assemblies[Assemblies in Red Hat documentation]
