[id="versioning-a-product_{context}"]
= Versioning a product

[role="_abstract"]
A product must have at least one product version assigned to it.

.Prerequisites

* You are logged in.
* The product to be versioned exists in {ProductName}.

.Procedure

. Navigate to menu:Products[Product Listing].

. Find the product and click the drop-down arrow>Product Details.

. Enter the following information:
  New Version:: This is the text that appears in {ProductShortName}, and the document preview.
  URL Fragment:: This string appears in the user-facing URL for any content that belongs to this product and version. A URL fragment can include letters, numbers, hyphens, periods and underscores.

. Click btn:[Save].

.Example

New Version:: 4.4 Beta
URL Fragment:: `4.4-beta`

After creating a product version *4.4-beta* and assigning a module the *.NET Core* product and version *4.4-beta*, the resulting URL for that module is: `\https://access.stage.redhat.com/documentation/en-us/topic/net_core/4.4-beta/<_module-UUID_>`
