[id="assigning-metadata-to-a-module_{context}"]
= Assigning metadata to a module

Assign metadata to a module for search engine optimization (SEO). SEO improves the findability of modules.

.Prerequisites

* You are logged in.
* The module to be assigned metadata has been imported to {ProductShortName}.

.Procedure

. Navigate to link:{LinkToSearchPage}[Search page].

. Click the name of the module you want to assign metadata.
+
If you do not see the module listed, search for the modules using the search box.

. In the list of module versions, click the three vertical dots next to the version of the module you want to assign metadata.

. Click *Edit metadata* to assign the following metadata: 
+
* *Product Name* - Select the Product and its Version that the module should be published for.
* *Document use case* - Select the verb that best describes the use case for the module..
* *Vanity URL fragment* - Enter a URL for the module.
* *Search keywords* - Enter the words that, when searched by users, should bring up the module in the user's search. This is optional.

. Click *Save*.

Metadata for the module is now assigned.
