[id="assigning-metadata-to-a-module_{context}"]
= Assigning metadata to {ContentTerm}

[role="_abstract"]
Assign metadata to {ContentTerm} to enable search engine optimization (SEO). SEO improves the findability of content. Assigned metadata also determines the URL at which the {ContentTerm} is published.

.Prerequisites

* You are logged in.
* The {ContentTerm} to be assigned metadata has been imported to {ProductShortName}.

.Procedure

. Navigate to link:{LinkToSearchPage}[Search page].

. Click the name of the {ContentTerm} to which you want to assign metadata.
+
If you do not see the {ContentTerm} listed, search for it using the search box.

. In the list of {ContentTerm} versions, click the vertical ellipsis next to the version of the {ContentTerm} you want to assign metadata.

. Click *Edit metadata* to assign the following metadata: 
+
* *Product Name* - Select the product and product version for the {ContentTerm}.
* *Document use case* - Select the verb that best describes the use case for the {ContentTerm}.
* *Vanity URL fragment* - (Optional) Enter a URL for the {ContentTerm}.
* *Search keywords* - (Optional) Enter any words or terms that users might use when searching for this content.

. Click *Save*.

The {ContentTerm} now includes metadata.
