[id="search-modules"]

= How to search Modules

The `Modules` tab allows you to search for modules in Pantheon both by simple keyword or free text search, and by applying a number of different filters to search and to sort the results.

.To perform a keyword or free text search:
. In the search bar at top right, enter a free text phrase or keywords.
. You can also add Boolean operators to the keywords to refine the search.
. Press `Enter` or click the search icon  to initiate the search.

.To add filters to the search, use any combination of the following:
* Select a Product name from the `Select a Product` drop down menu.
* Select a version number from the `Select a Version` drop down menu.
* Select a module type from the third drop down menu (`All`, `Concept`, `Procedure`, or `Reference`).
* Select a property from the fourth drop down menu (`Uploaded date`, `Title`, `Updated date`, or `Module type`)
* Press `Enter` or click the search icon to initiate the search.

.Viewing search results
The search results are presented in a table organized into columns with the following headings:

* `Title` - the module title
* `Published` - the publication status, `Published` or `Not published`
* `Draft uploaded` - the date the draft was uploaded
* `Module Type` - the module type, `Concept`, `Procedure`, or `Reference`
* A sorting button allows you to quickly change the sorting order of search results from A-Z to Z-A.
