[id="creating-a-product_{context}"]
= Creating a product

[role="_abstract"]
A product must exist in {ProductName} before you can assign a product name to the metadata of a module or assembly. If the product doesn't already exist, you need to create one.

.Prerequisites

* You are logged in.
* You have Publisher permissions.

.Procedure

. Navigate to menu:Products[New Product].
. Enter the following information, items marked with a star are mandatory:
  Product Name *:: The text that appears in {ProductShortName}, the document preview, and in user-facing content.
  Product URL Fragment *:: This string appears in the user-facing URL for any content that belongs to this product and version. A URL fragment can include letters, numbers, hyphens, periods and underscores.
  Product Description:: A description of the product.
  Product Version *:: The product version.
  Version URL Fragment *:: This string appears in the user-facing URL for any content that belongs to this product and version. A URL fragment can include letters, numbers, hyphens, periods and underscores.
. Click btn:[Save].

.Example

Product Name: .NET Core
Product URL Fragment: `net_core`
Product Description: Documentation for the .NET Core framework.
Product Version: 4.4-Beta
Version URL Fragment: 4.4-beta

Entering the above information creates a {ProductShortName} product named `.NET Core`. The URL for documentation that is associated with this product includes the URL Fragment `net_core` to identify the product, and the Version URL Fragment is `4.4-beta`. The resulting URL for that module is:

`\https://access.stage.redhat.com/documentation/en-us/topic/net_core/4.4-beta/_module-UUID_`

// .Additional resources
// link:placeholder.url.com[Creating a product version]
