[id="assigning-metadata-to-a-module_{context}"]
= Assigning metadata to {ContentTerm}
:_module-type: PROCEDURE

[role="_abstract"]
Assign metadata to your content so that {ProductShortName} can publish it under the correct product and version on the {PublishingPortal}.

Metadata in modules and assemblies does the following:

* Enables external search engine optimization (SEO) for published content, making it easier for customers to find content.
* Enables (SEO) within {ProductShortName}'s  search engine, making it easier for {ProductShortName} users and administrators to find content.
* Defines the URL at which the {ContentTerm} is published.

[NOTE]
====
Module type is also metadata. You define the module's type directly within the module. See xref:identifying-module-types_assembly-help[Identifying {ProductShortName} module types].
====

.Prerequisites

* You are logged in to {ProductShortName}.
* The {ContentTerm} to be assigned metadata has been imported into {ProductShortName}.

.Procedure

. Navigate to the link:{LinkToSearchPage}[Search page].

. Click the item to which you want to assign metadata.
+
If you do not see the {ContentTerm} listed, search for it using the search box.

. In the list of {ContentTerm} versions, click the vertical ellipsis next to the version of the {ContentTerm} you want to assign metadata.

. Click *Edit metadata* to assign the following metadata:
+
* *Product Name* - Select the product and product version for the {ContentTerm}.
* *Document use case* - Select the verb that best describes the use case for the {ContentTerm}.
* *Vanity URL fragment* - (Optional) Enter a URL for the {ContentTerm}.
* *Search keywords* - (Optional) Enter any words or terms that users might use when searching for this content.

. Click *Save*.

The {ContentTerm} now includes metadata.
