[id='search-view-results_{context}']

= Viewing search results

[role="_abstract"]
{ProductName} displays search results in two tables, *Modules* and *Assemblies*. which have the following columns:

* *Title*
* *Repository* : the repository in which content is located
* *Upload date* : the date on which the latest draft of the content was uploaded
* *Last Published date* : the date the content was last published

You can select the number of results you want to be displayed per page.


== Viewing content details

You can see additional details for each content item that is displayed in your search results.

.Procedure

In the Search results table, click the link of a content item.
+
{ProductName} displays the following information:

* *Module*: Complete directory path of the module's .adoc file.
* *Product*
* *Module type*
* *First published date*
* *Last published date*

== Previewing text

You can see the text of the latest draft of a module or an assembly using the {ProductName} the search engine.

.Procedure

. In the Search results table, click the link of a content item.
. Click *Preview* in the gray text box in the lower half of the page.

{ProductName} displays the text, rendered similarly to its appearance in the Customer Portal.
