[id='identifying-module-types_{context}']
= Identifying {ProductShortName} module types
:pantheon-module-type: REFERENCE

[role="_abstract"]
In {ProductShortName}, each module must be identified by type: concept, procedure, or reference.

For information about module types, see https://redhat-documentation.github.io/modular-docs/#writing-mod-docs[Types of modules in Red Hat documentation].

Identify the module type by using either one or both of the following:

* The correct attribute after the module's title
* The correct prefix in the module's name

Using the correct attribute (preferred method)::

Enter the correct attribute in the line immediately following the module's title, choosing among the following:

* `:pantheon-module-type: CONCEPT`
* `:pantheon-module-type: PROCEDURE`
* `:pantheon-module-type: REFERENCE`

====
.Example

`= Identifying {ProductShortName} module types :pantheon-module-type: REFERENCE`

====

Using the correct prefix::

Begin the file names of modules with the correct prefix, choosing among the following:

* `con_`
* `proc_`
* `ref_`

====
.Example

`ref_identifying-module-types.adoc`

====

How {ProductShortName} {ProductNumber}  checks identifiers::

{ProductShortName} {ProductNumber} first checks for the module's attribute. Any value other than those specified is ignored. If there is no valid attribute, {ProductShortName} {ProductNumber} then checks the module's prefix. If both a valid attribute and prefix exist, {ProductShortName} {ProductNumber}  uses the attribute.
