[id='pantheon-user-interface_{context}']
= {ProductShortName} user interface


The user interface is organized with a main work area, an upper toolbar with `Help` and `Log In` buttons, a show/hide button for displaying the sidebar, and a tabbed sidebar with the following tabs:

* `Modules` - Use this tab to create new document modules, search for, edit, or delete modules.
** `Search` - Provides advanced search options, including keyword search, search by product name, product version, document module  type (procedure, concept, reference) and upload date.
*** Select a module check box to delete the selected module.
*** Select a module name to view the module status and details, and publish, unpublish, preview or view the module in the customer portal.
*** A drop-down menu allows editing the moduleMetadata of a module.
** `Git Import` - Use this tab to import a module file directly from GitHub.
*** Enter the repository URL and branch name in the provided fields and click `Submit`.
* `Products` - Use this tab to view a list of product titles and details, and create new product titles.
** `Product Listing` - Lists the available product titles. A drop down menu allows viewing product details.
** `New Product` - Use this tab to create a new product title.
*** Enter a product name and description in the provided fields and click `Save`.
