[id='identifying-module-types_{context}']
= Identifying {ProductShortName} {ProductNumber} module types
:pantheon-module-type: REFERENCE

In {ProductShortName} {ProductNumber}, each module must be identified by type: concept, procedure, or reference.

For information about module types, see https://redhat-documentation.github.io/modular-docs/#writing-mod-docs[Types of modules in Red Hat documentation].

Identification is done by using either one or both of the following:

* The correct attribute after the module's title
* The correct prefix in the module's name

Use of the correct attribute (preferred method)::

One of the following attributes should be entered in the line immediately following the module's title:

* `:pantheon-module-type: CONCEPT`
* `:pantheon-module-type: PROCEDURE`
* `:pantheon-module-type: REFERENCE`

====
.Example

`= Identifying {ProductShortName} module types :pantheon-module-type: REFERENCE`

====

Use of the correct prefix::

File names of modules should start with the appropriate choice among the following

* `con_`
* `proc_`
* `ref_`

====
.Example

`ref_identifying-module-types.adoc`

====

How {ProductShortName} {ProductNumber}  checks identifiers::

{ProductShortName} {ProductNumber} first checks for the module's attribute. Any value other than those specified is ignored. If there is no valid attribute, {ProductShortName} {ProductNumber} then checks the module's prefix. If both a valid attribute and prefix exist, {ProductShortName} {ProductNumber}  uses the attribute.
